name: "Automatic Release"

on:
 push:
   tags:
     - "v*"

jobs:
 release:
   name: "Release"
   runs-on: "ubuntu-latest"

   steps:
     - name: "Checkout code"
       uses: actions/checkout@v4

     - name: "Install Dependencies"
       run: npm install

     - name: "Build"
       run: npm run build

     - name: "Create Release"
       uses: "marvinpinto/action-automatic-releases@latest"
       with:
         repo_token: "${{ secrets.GITHUB_TOKEN }}"
         prerelease: false
         files: |
           gfn-linux.zip
           gfn-linux.AppImage