name: "release"

on:
 push:
   branches:
     - "main"

jobs:
 pre-release:
   name: "Auto Release"
   runs-on: "ubuntu-latest"

   steps:
     - name: "Checkout code"
       uses: actions/checkout@v2

     - name: "Setup Node.js"
       uses: actions/setup-node@v2
       with:
         node-version: '16'

     - name: "Install Dependencies"
       run: npm install

     - name: "Build & Publish"
       run: npm run build

     - name: "Release"
       uses: "marvinpinto/action-automatic-releases@latest"
       with:
         repo_token: "${{ secrets.GITHUB_TOKEN }}"
         automatic_release_tag: "latest"
         prerelease: true
         title: "Latest Build"
         files: |
           dist/gfn-linux.zip
           dist/gfn-linux.AppImage
           dist/gfn-linux.deb
